timezone: "America/Los_Angeles"

categories: [ "sci-fi", "tech", "mystic", "geometry", "nature", "neo-noir", "watercolor", "cosmic-minimal" ]

rotation_minutes: 180   # category index = floor(now_min / rotation_minutes) % len(categories)

prompt_generation:
  provider: "dummy"        # openai | dummy
  model: "gpt-5"            # default model for base prompt, variants, and alt text
  num_prompt_variants: 3        # 1 base -> 3 variants
  # system/style rules enforced at runtime (no real people/logos/NSFW, negative prompts, style hints)

image_generation:
  provider_order: ["fal", "replicate"]
  model_fal: ["fal-ai/gemini-25-flash-image", "fal-ai/bytedance/seedream/v3/text-to-image", "fal-ai/imagen4/preview/ultra"]     # list of models to use
  model_replicate: ["google/gemini-2.5-flash-image", "bytedance/seedream-3", "google/imagen-4-ultra"]   # list of models to use
  retries_per_image: 2

ranking:
  # final = w_brightness * B_norm + w_entropy * H_norm + w_aesthetic * Aesthetic
  w_brightness: 0.25
  w_entropy: 0.25
  w_aesthetic: 0.50

  # sanity floors (discard if violated)
  entropy_min: 3.5
  brightness_min: 10
  brightness_max: 245

  # dedupe against recent manifest pHashes
  phash_distance_min: 6

aesthetic_scoring:
  provider: "replicate"
  model: "methexis-inc/img2aestheticscore:ec5029694b29e51fa9e5b794d73ba8103569d5d3ef3d60b7a8fdef18b9997b90"  # Example aesthetic scoring model
  score_min: 1.0    # Minimum expected score from the model
  score_max: 10.0    # Maximum expected score from the model

upscale:
  enabled: true
  provider: "fal"          # or "fal"
  model: "fal-ai/esrgan"        # pick your exact model
  factor: 2

# output sizes — edit this list to change wallpaper variants without code changes
wallpaper_variants:
  - {name: "square_1x1_2k",        w: 2048, h: 2048}
  - {name: "phone_9x16_2k",        w: 1125, h: 2000}
  - {name: "phone_20x9_3.2k",      w: 1440, h: 3200}
  - {name: "desktop_16x9_1080p",   w: 1920, h: 1080}
  - {name: "desktop_16x9_1440p",   w: 2560, h: 1440}
  - {name: "desktop_16x9_4k",      w: 3840, h: 2160}
  - {name: "desktop_16x10_1600p",  w: 2560, h: 1600}
  - {name: "ultrawide_21x9",       w: 3440, h: 1440}

alerts:
  enabled: true
  webhook_url_env: "ALERT_WEBHOOK_URL"
