# Timezone for date/time operations and category rotation scheduling
timezone: "America/Los_Angeles"

# Comprehensive list of image categories/themes organized by genre - determines the subject matter and thematic content for generated images, rotated automatically based on rotation_minutes
categories: [
    # Cinematic & Atmosphere
    "neo-noir", "film-noir", "cyberpunk", "retrowave", "synthwave", "vaporwave",
    "dreamlike", "ethereal", "psychedelic", "surreal", "dystopian", "utopian",
    "cinematic-still", "analog-film", "hdr-photography",

    # Sci-Fi & Futuristic
    "sci-fi", "space-opera", "futurism", "tech", "ai-fusion", "post-apocalyptic",
    "mecha", "biomechanical", "robotic", "cyborg", "space-colony", "time-travel",

    # Fantasy & Mystic
    "mystic", "dark-fantasy", "fairytale", "mythology", "arcane-symbols",
    "steampunk", "dieselpunk", "solarpunk", "magical-realism", "eldritch",
    "alchemy", "dreamscape",

    # Nature & Environment
    "nature", "cosmic-minimal", "landscape", "underwater", "forest", "desert",
    "mountains", "volcano", "tundra", "aurora", "celestial", "bioluminescence",
    "bonsai", "flora-botanical", "microcosm",

    # Abstract & Geometry
    "geometry", "fractal", "low-poly", "op-art", "sacred-geometry",
    "generative-art", "data-visualization", "kaleidoscopic", "mandala",
    "abstract-expressionism", "glitch-art", "minimalism",

    # Cultural & Historical
    "renaissance", "baroque", "art-nouveau", "art-deco", "bauhaus",
    "ukiyo-e", "byzantine", "tribal-patterns", "indigenous-art",
    "cave-painting", "medieval-illumination", "gothic",

    # Artistic Mediums
    "watercolor", "oil-painting", "acrylic", "ink-wash", "charcoal",
    "line-art", "vector-art", "pixel-art", "collage", "mixed-media",
    "graffiti", "street-art", "stained-glass", "mosaic",

    # Pop & Contemporary
    "pop-art", "comic-book", "anime", "manga", "chibi", "graphic-novel",
    "conceptual-art", "installation-art", "fashion-editorial", "album-cover",
    "poster-design", "tattoo-art", "toy-design"
]

# Comprehensive list of art styles that can be applied to generated images - used by the prompt generation system to add artistic style variations to image prompts
art_styles: [
    # Traditional Fine Art Styles
    "Realism", "Impressionism", "Post-Impressionism", "Expressionism", "Fauvism",
    "Cubism", "Futurism", "Surrealism", "Dadaism", "Abstract Expressionism",
    "Minimalism", "Symbolism", "Pointillism",

    # Painting Mediums & Techniques
    "Oil painting", "Watercolor", "Acrylic painting", "Gouache painting",
    "Ink wash (Sumi-e)", "Fresco", "Tempera", "Encaustic", "Impasto", "Airbrush",

    # Modern & Contemporary Styles
    "Pop Art", "Photorealism", "Hyperrealism", "Conceptual Art", "Op Art",
    "Kinetic Art", "Digital Glitch Art", "Vaporwave", "Synthwave", "Retrowave",
    "Low-poly", "Generative Art",

    # Graphic & Illustration Styles
    "Line Art", "Flat Design", "Cartoon", "Comic Book", "Anime", "Manga",
    "Chibi", "Graphic Novel style", "Pixel Art", "Vector Art", "Stippling",
    "Cross-hatching",

    # Cultural & Historical Styles
    "Renaissance", "Baroque", "Rococo", "Neoclassicism", "Romanticism",
    "Art Nouveau", "Art Deco", "Bauhaus", "Brutalism", "Ukiyo-e",
    "Persian Miniature", "Byzantine", "Gothic", "Medieval Illumination",

    # Photography & Cinematic Styles
    "Black and white photography", "Sepia tone", "Film noir",
    "Cinematic still frame", "HDR photography", "Long-exposure",
    "Macro photography", "Tilt-shift", "Polaroid aesthetic", "Daguerreotype",

    # Atmospheric & Experimental Styles
    "Dreamlike", "Ethereal", "Psychedelic", "Cosmic", "Astral",
    "Biomechanical", "Cyberpunk", "Steampunk", "Dieselpunk", "Solarpunk",
    "Dark Fantasy", "Whimsical", "Fairytale", "Collage", "Mixed Media"
]


# Category selection method: "time" for time-based rotation, "random" for random selection
category_selection_method: "random"

# Minutes each category stays active before rotating to next - category index = floor(now_min / rotation_minutes) % len(categories)
# Only used when category_selection_method is "time"
rotation_minutes: 180

prompt_generation:
  provider: "openai"        # Prompt generation provider: "openai" for GPT models, "dummy" for testing
  model: "gpt-5"            # AI model for generating base prompts, variants, and alt text
  num_prompt_variants: 3    # Number of prompt variations to generate from each base prompt (1 base -> 3 variants)
  # System/style rules enforced at runtime: no real people/logos/NSFW content, includes negative prompts, aesthetic style hints

image_generation:
  provider_order: ["fal", "replicate"]  # Order to try image generation providers - FAL first, then Replicate as fallback
  model_fal: ["fal-ai/gemini-25-flash-image", "fal-ai/bytedance/seedream/v3/text-to-image", "fal-ai/imagen4/preview/ultra"]     # FAL AI models to use for image generation
  model_replicate: ["google/gemini-2.5-flash-image", "bytedance/seedream-3", "google/imagen-4-ultra"]   # Replicate models as fallback options
  retries_per_image: 2      # Number of retry attempts per image generation request before giving up

ranking:
  # Image scoring weights for final ranking: final_score = w_brightness * brightness_norm + w_entropy * entropy_norm + w_aesthetic * aesthetic_score + w_local_quality * local_quality_score
  w_brightness: 0.25        # Weight for normalized brightness score (0-1)
  w_entropy: 0.25           # Weight for normalized entropy/complexity score (0-1) 
  w_aesthetic: 0.50         # Weight for aesthetic quality score (0-1)
  w_local_quality: 0.20     # Weight for local quality score (0-1) - sharpness and exposure

  # Quality thresholds - images failing these are discarded before ranking
  entropy_min: 3.5          # Minimum entropy (visual complexity) - filters out overly simple/flat images
  brightness_min: 10        # Minimum average brightness (0-255) - filters out too-dark images
  brightness_max: 245       # Maximum average brightness (0-255) - filters out overexposed images

  # Duplicate detection using perceptual hashing
  phash_distance_min: 6     # Minimum Hamming distance between perceptual hashes to avoid near-duplicates

aesthetic_scoring:
  provider: "replicate"     # Provider for aesthetic quality scoring
  model: "methexis-inc/img2aestheticscore:ec5029694b29e51fa9e5b794d73ba8103569d5d3ef3d60b7a8fdef18b9997b90"  # Aesthetic scoring model endpoint
  score_min: 1.0            # Minimum expected aesthetic score from the model (for normalization)
  score_max: 10.0           # Maximum expected aesthetic score from the model (for normalization)

local_quality:
  resize_long: 768          # Resize images to this long side for quality assessment (faster processing)
  min_side: 512             # Minimum dimension for either width or height (hard floor)
  ar_min: 0.5               # Minimum aspect ratio (width/height) - reject ultra-tall images
  ar_max: 2.0               # Maximum aspect ratio (width/height) - reject ultra-wide images
  sharpness_min: 120.0      # Minimum Variance of Laplacian for sharpness (hard floor)
  sharpness_good: 600.0     # VoL value considered "good" sharpness (score = 1.0)
  clip_max: 0.20            # Maximum allowed clipping fraction (shadows + highlights, hard floor)

upscale:
  enabled: true             # Whether to upscale winning images before creating wallpaper variants
  provider: "fal"           # Upscaling provider: "fal", "replicate", or "dummy_local" for testing
  model: "fal-ai/esrgan"    # Specific upscaling model to use (e.g., Real-ESRGAN variants)
  factor: 2                 # Upscaling factor (2x, 4x, etc.)

# Output wallpaper variants - edit this list to change sizes without code changes
# Each variant specifies: name (for file naming), width, and height in pixels
wallpaper_variants:
  - {name: "square_1x1_2k",        w: 2048, h: 2048}    # Square format for social media, avatars
  - {name: "phone_9x16_2k",        w: 1125, h: 2000}    # Portrait phone wallpaper (iPhone-style)
  - {name: "phone_20x9_3.2k",      w: 1440, h: 3200}    # Tall phone wallpaper (Android ultra-wide)
  - {name: "desktop_16x9_1080p",   w: 1920, h: 1080}    # Standard desktop 1080p
  - {name: "desktop_16x9_1440p",   w: 2560, h: 1440}    # Desktop 1440p (2K)
  - {name: "desktop_16x9_4k",      w: 3840, h: 2160}    # Desktop 4K resolution
  - {name: "desktop_16x10_1600p",  w: 2560, h: 1600}    # Desktop 16:10 aspect ratio
  - {name: "ultrawide_21x9",       w: 3440, h: 1440}    # Ultrawide monitor format

alerts:
  enabled: false             # Whether to send webhook notifications for successes/failures
  webhook_url_env: "ALERT_WEBHOOK_URL"  # Environment variable name containing the webhook URL (e.g., Discord, Slack)
